CREATE TABLE public.profiles (id uuid PRIMARY KEY, first_name text, last_name text, email text, status text NOT NULL DEFAULT 'active', last_login_at timestamptz, company_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, description text, is_system boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.roles TO authenticated; GRANT ALL ON public.roles TO service_role;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, group_name text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permissions TO authenticated; GRANT ALL ON public.permissions TO service_role;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role_id uuid NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, role_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.role_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role_id uuid NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE, permission_id uuid NOT NULL REFERENCES public.permissions(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(role_id, permission_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.role_permissions TO authenticated; GRANT ALL ON public.role_permissions TO service_role;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.modules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, description text, icon text NOT NULL DEFAULT 'Box', version text NOT NULL DEFAULT '1.0.0', route text, status text NOT NULL DEFAULT 'inactive', enabled boolean NOT NULL DEFAULT false, configuration jsonb NOT NULL DEFAULT '{}'::jsonb, parent_id uuid REFERENCES public.modules(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.modules TO authenticated; GRANT ALL ON public.modules TO service_role;
ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.module_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), module_id uuid NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE, code text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(module_id, code));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_permissions TO authenticated; GRANT ALL ON public.module_permissions TO service_role;
ALTER TABLE public.module_permissions ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.module_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_module_id uuid REFERENCES public.modules(id) ON DELETE CASCADE, target_module_id uuid REFERENCES public.modules(id) ON DELETE CASCADE, connection_type text NOT NULL DEFAULT 'module_to_core', status text NOT NULL DEFAULT 'active', permissions jsonb NOT NULL DEFAULT '[]'::jsonb, configuration jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_connections TO authenticated; GRANT ALL ON public.module_connections TO service_role;
ALTER TABLE public.module_connections ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.activity_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, actor_label text, action text NOT NULL, entity_type text, entity_id text, description text, status text NOT NULL DEFAULT 'success', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT ON public.activity_logs TO authenticated; GRANT ALL ON public.activity_logs TO service_role;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.system_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, value jsonb NOT NULL DEFAULT '{}'::jsonb, group_name text NOT NULL DEFAULT 'general', description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_settings TO authenticated; GRANT ALL ON public.system_settings TO service_role;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.company (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, logo_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.company TO authenticated; GRANT ALL ON public.company TO service_role;
ALTER TABLE public.company ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX company_singleton_idx ON public.company ((true));
ALTER TABLE public.profiles ADD CONSTRAINT profiles_company_fk FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE SET NULL;
CREATE TABLE public.subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.company(id) ON DELETE CASCADE, plan text NOT NULL CHECK(plan IN ('MONTHLY','SEMI_ANNUAL','ANNUAL')), start_date date NOT NULL DEFAULT CURRENT_DATE, end_date date NOT NULL, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','EXPIRED','SUSPENDED','CANCELLED')), notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.subscriptions TO authenticated; GRANT ALL ON public.subscriptions TO service_role;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX subscriptions_one_active_idx ON public.subscriptions(company_id) WHERE status = 'ACTIVE';
CREATE TABLE public.subscription_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subscription_id uuid NOT NULL REFERENCES public.subscriptions(id) ON DELETE CASCADE, event text NOT NULL, from_plan text, to_plan text, from_status text, to_status text, actor_id uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT ON public.subscription_events TO authenticated; GRANT ALL ON public.subscription_events TO service_role;
ALTER TABLE public.subscription_events ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.user_module_access (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, module_id uuid NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,module_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_module_access TO authenticated; GRANT ALL ON public.user_module_access TO service_role;
ALTER TABLE public.user_module_access ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.has_role_slug(_user_id uuid,_slug text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles ur JOIN public.roles r ON r.id=ur.role_id WHERE ur.user_id=_user_id AND r.slug=_slug) $$;
CREATE OR REPLACE FUNCTION public.has_permission(_user_id uuid,_code text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles ur JOIN public.role_permissions rp ON rp.role_id=ur.role_id JOIN public.permissions p ON p.id=rp.permission_id WHERE ur.user_id=_user_id AND p.code=_code) $$;
CREATE OR REPLACE FUNCTION public.can_see_module(_uid uuid,_module_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_role_slug(_uid,'super-admin') OR public.has_permission(_uid,'modules.configure') OR EXISTS(SELECT 1 FROM public.user_module_access WHERE user_id=_uid AND module_id=_module_id) $$;
REVOKE EXECUTE ON FUNCTION public.has_role_slug(uuid,text),public.has_permission(uuid,text),public.can_see_module(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.has_role_slug(uuid,text),public.has_permission(uuid,text),public.can_see_module(uuid,uuid) TO authenticated;
CREATE OR REPLACE FUNCTION public.bootstrap_current_user(_first_name text DEFAULT NULL,_last_name text DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE _uid uuid:=auth.uid(); _email text; _role_id uuid; BEGIN IF _uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; SELECT email,raw_user_meta_data->>'first_name',raw_user_meta_data->>'last_name' INTO _email,_first_name,_last_name FROM auth.users WHERE id=_uid; INSERT INTO public.profiles(id,email,first_name,last_name,last_login_at) VALUES(_uid,_email,_first_name,_last_name,now()) ON CONFLICT(id) DO UPDATE SET last_login_at=now(),email=EXCLUDED.email; IF NOT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_uid) THEN SELECT id INTO _role_id FROM public.roles WHERE slug='viewer'; IF _role_id IS NOT NULL THEN INSERT INTO public.user_roles(user_id,role_id) VALUES(_uid,_role_id) ON CONFLICT DO NOTHING; END IF; END IF; INSERT INTO public.activity_logs(user_id,actor_label,action,entity_type,description) VALUES(_uid,_email,'user.login','auth','User signed in'); END $$;
REVOKE EXECUTE ON FUNCTION public.bootstrap_current_user(text,text) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.bootstrap_current_user(text,text) TO authenticated;
CREATE OR REPLACE FUNCTION public.check_access() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$ DECLARE _uid uuid:=auth.uid(); _p record; _s record; BEGIN IF _uid IS NULL THEN RETURN jsonb_build_object('allowed',false,'reason','not_authenticated'); END IF; IF public.has_role_slug(_uid,'super-admin') THEN RETURN jsonb_build_object('allowed',true); END IF; SELECT company_id,status INTO _p FROM public.profiles WHERE id=_uid; IF _p.status IS DISTINCT FROM 'active' THEN RETURN jsonb_build_object('allowed',false,'reason','account_disabled'); END IF; IF _p.company_id IS NULL THEN RETURN jsonb_build_object('allowed',false,'reason','no_company'); END IF; SELECT status,end_date INTO _s FROM public.subscriptions WHERE company_id=_p.company_id ORDER BY created_at DESC LIMIT 1; IF NOT FOUND THEN RETURN jsonb_build_object('allowed',false,'reason','no_subscription'); END IF; IF _s.end_date<CURRENT_DATE OR _s.status='EXPIRED' THEN RETURN jsonb_build_object('allowed',false,'reason','subscription_expired'); END IF; IF _s.status<>'ACTIVE' THEN RETURN jsonb_build_object('allowed',false,'reason','subscription_'||lower(_s.status)); END IF; RETURN jsonb_build_object('allowed',true); END $$;
REVOKE EXECUTE ON FUNCTION public.check_access() FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.check_access() TO authenticated;
CREATE POLICY profiles_select ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.has_permission(auth.uid(),'users.view'));
CREATE POLICY profiles_insert ON public.profiles FOR INSERT TO authenticated WITH CHECK(id=auth.uid() OR public.has_permission(auth.uid(),'users.create'));
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid() OR public.has_permission(auth.uid(),'users.edit')) WITH CHECK(id=auth.uid() OR public.has_permission(auth.uid(),'users.edit'));
CREATE POLICY roles_select ON public.roles FOR SELECT TO authenticated USING(true);
CREATE POLICY roles_write ON public.roles FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'roles.manage')) WITH CHECK(public.has_permission(auth.uid(),'roles.manage'));
CREATE POLICY permissions_select ON public.permissions FOR SELECT TO authenticated USING(true);
CREATE POLICY permissions_write ON public.permissions FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'permissions.manage')) WITH CHECK(public.has_permission(auth.uid(),'permissions.manage'));
CREATE POLICY user_roles_select ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_permission(auth.uid(),'users.view'));
CREATE POLICY user_roles_write ON public.user_roles FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'users.edit')) WITH CHECK(public.has_permission(auth.uid(),'users.edit'));
CREATE POLICY role_permissions_select ON public.role_permissions FOR SELECT TO authenticated USING(true);
CREATE POLICY role_permissions_write ON public.role_permissions FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'roles.manage')) WITH CHECK(public.has_permission(auth.uid(),'roles.manage'));
CREATE POLICY modules_select ON public.modules FOR SELECT TO authenticated USING(public.can_see_module(auth.uid(),id));
CREATE POLICY modules_insert ON public.modules FOR INSERT TO authenticated WITH CHECK(public.has_permission(auth.uid(),'modules.install'));
CREATE POLICY modules_update ON public.modules FOR UPDATE TO authenticated USING(public.has_permission(auth.uid(),'modules.configure')) WITH CHECK(public.has_permission(auth.uid(),'modules.configure'));
CREATE POLICY modules_delete ON public.modules FOR DELETE TO authenticated USING(public.has_permission(auth.uid(),'modules.install'));
CREATE POLICY module_permissions_select ON public.module_permissions FOR SELECT TO authenticated USING(true);
CREATE POLICY module_permissions_write ON public.module_permissions FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'modules.configure')) WITH CHECK(public.has_permission(auth.uid(),'modules.configure'));
CREATE POLICY connections_select ON public.module_connections FOR SELECT TO authenticated USING(public.has_permission(auth.uid(),'connections.view'));
CREATE POLICY connections_write ON public.module_connections FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'connections.edit')) WITH CHECK(public.has_permission(auth.uid(),'connections.edit'));
CREATE POLICY logs_select ON public.activity_logs FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_permission(auth.uid(),'logs.view'));
CREATE POLICY logs_insert ON public.activity_logs FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid());
CREATE POLICY settings_select ON public.system_settings FOR SELECT TO authenticated USING(true);
CREATE POLICY settings_write ON public.system_settings FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'settings.manage')) WITH CHECK(public.has_permission(auth.uid(),'settings.manage'));
CREATE POLICY company_select ON public.company FOR SELECT TO authenticated USING(true);
CREATE POLICY company_write ON public.company FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'company.manage')) WITH CHECK(public.has_permission(auth.uid(),'company.manage'));
CREATE POLICY subscriptions_select ON public.subscriptions FOR SELECT TO authenticated USING(true);
CREATE POLICY subscriptions_write ON public.subscriptions FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'subscription.manage')) WITH CHECK(public.has_permission(auth.uid(),'subscription.manage'));
CREATE POLICY subscription_events_select ON public.subscription_events FOR SELECT TO authenticated USING(true);
CREATE POLICY subscription_events_insert ON public.subscription_events FOR INSERT TO authenticated WITH CHECK(public.has_permission(auth.uid(),'subscription.manage'));
CREATE POLICY uma_select ON public.user_module_access FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_permission(auth.uid(),'users.view'));
CREATE POLICY uma_write ON public.user_module_access FOR ALL TO authenticated USING(public.has_permission(auth.uid(),'users.edit')) WITH CHECK(public.has_permission(auth.uid(),'users.edit'));